######################################################################
# Automatically generated by qmake (3.0) Fri May 20 19:52:25 2016
######################################################################

TEMPLATE = app
TARGET = ../build/ipc_gui
INCLUDEPATH += .
QT += widgets
OBJECTS_DIR = ../build

# Input
FORMS += ipc.ui manager.ui
SOURCES += main.cpp ipc.cpp manager.cpp
HEADERS += ipc.hpp manager.hpp
